The format is required by FrameworkBundle
Is the format is missing 

InvalidArgumentException: Template name "MktUserBundle:Registration:email.twig" is not valid (format is "bundle:section:template.format.engine")